/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */

var findTheDifference = function(s, t) {
    let i = 0;
    let j = 0;

    while (j < t.length) {
        if (s[i] === t[j]) {
            s = s.slice(1);
            t = t.slice(0, j) + t.slice(j + 1);
            j = 0;
        } else {
            j++;
        }
    }

    return t;
};

console.log(findTheDifference("abc","abcd"))